// LISTS
export const FETCH_LISTS_START = 'FETCH_LISTS_START';
export const FETCH_LISTS_SUCCESS = 'FETCH_LISTS_SUCCESS';
export const FETCH_LISTS_ERROR = 'FETCH_LISTS_ERROR';
export const ADD_LIST_START = 'ADD_LIST_START';
export const ADD_LIST_SUCCESS = 'ADD_LIST_SUCCESS';
export const ADD_LIST_ERROR = 'ADD_LIST_ERROR';

// LIST ITEMS
export const FETCH_LIST_ITEMS_START = 'FETCH_LIST_ITEMS_START';
export const FETCH_LIST_ITEMS_SUCCESS = 'FETCH_LIST_ITEMS_SUCCESS';
export const FETCH_LIST_ITEMS_ERROR = 'FETCH_LIST_ITEMS_ERROR';
export const ADD_LIST_ITEM_START = 'ADD_LIST_ITEM_START';
export const ADD_LIST_ITEM_SUCCESS = 'ADD_LIST_ITEM_SUCCESS';
export const ADD_LIST_ITEM_ERROR = 'ADD_LIST_ITEM_ERROR';
